### ISSUE TITLE
Subir notas tomadas en clase

### ISSUE THREAD

**Issue by jruitti** [CarlosQuinteros/PROG-III#1]
Subir las notas tomadas en la clase del miércoles 13/09/17. @CarlosQuinteros

**Comment by CarlosQuinteros** [comment]
Profe las notas fueron subidas en la carpeta correspondiente "Notas"

**Comment by jruitti** [comment]
Perfecto. No lo había visto. Mala mía.

Cierro el issue. Gracias!
