### ISSUE TITLE
Error linea 26 clase EnfermedadPaciente

### ISSUE THREAD

**Issue by CarlosQuinteros** [CarlosQuinteros/PROG-III#2]
@jruitti Hola profe, me sale un error "target entity is not defined" al colocar la anotación "ManyToOne" como lo indica el diagrama de clases, sin embargo al colocar "OneToMany" no da error. ¿A qué se debe esto?

Clase: EnfermedadPaciente
Línea 26 @OneToMany (debería ser ManyToOne)
	private List<modelo.Medicacion> medicacion;

**Comment by jruitti** [comment]
Hola! **Esta mal el diagrama**. Es OneToMany ya que EnfermedadPaciente puede tener mas de una Medicación, pero la Medicación corresponde a una EnfermedadPaciente. Ahi corrijo el diagrama.

**Comment by CarlosQuinteros** [comment]
Listo profe muchas gracias!
