### ISSUE TITLE
Consulta sobre EntityManager.persist

### ISSUE THREAD

**Issue by CarlosQuinteros** [CarlosQuinteros/PROG-III#3]
Hola @jruitti, tengo un problema con la inserción de una raza la cual tiene asociada la especie.
En el main primero persisto la especie con:
Especie e = new Especie ("Canino");
FacadePersistencia.crearEspecie(e);
y luego creo la raza y persisto pasándole la especie "e" previamente creada.
Raza r = new Raza("Pastor Aleman", e);
FacadePersistencia.crearRaza(r);
Aquí salta un error ya que está queriendo persistir mediante la estrategia cascade la especie e que ya tiene un id, por lo tanto me sale "Ya existe la llave (idEspecie) = x"
¿Cómo podría resolver esta situación? ya que pensando en lo que viene como lo es la parte grafica, el usuario al crear una raza seleccionara la especie correspondiente de las ya cargadas previamente y evitar duplicados.
Desde ya muchas gracias! Saludos

**Comment by jruitti** [comment]
Lo tenes commiteado al proyecto? Asi lo reviso

**Comment by CarlosQuinteros** [comment]
Si profe está en el remoto, revíselo sin problemas
